services:
  app:
    image: ghcr.io/notishaan/statuspulse:latest
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - statuspulse_net

  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - statuspulse_net

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - statuspulse_net

  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: always
    volumes:
      - kuma_data:/app/data
    networks:
      - statuspulse_net

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - statuspulse_net

networks:
  statuspulse_net:
    name: statuspulse_net
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
  kuma_data:
